/*let num1= prompt("enter the first number")
let num2 =prompt ("Enter the second number")
console.log(`the som of the tow numbers is ${num1+num2}`)
let age = prompt("enter the age")
if (age<=0 || age>=100){
    console.log(`you are not alive`)
}*/

/*let num = prompt("enter the number")
if(num %2 ==0){
    console.log("the number is even ")
}
else{
    console.log("the number is odd")
}
*/
/*
let mark = prompt("enter your mark ")
if(mark > 60){
    console.log("YOU HAVE PASSET")
    if(mark >=90 && mark <=100){
        console.log("your grade is A ");
    }
    else if(mark >=80 && mark <90){
        console.log("your grade is B ");
    }
    else if(mark >=70 && mark <80){
        console.log("your grade is C ");
    }
    else if(mark >=60 && mark <70){
        console.log(" your grade is D ")
    }
}
else{
    console.log("YOU HAVE FAILED");
}
*/